# Generated by Django 2.0.2 on 2018-02-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=15)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=15)),
                ('bio', models.TextField(help_text='Your brief history', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of your blog', max_length=225)),
                ('description', models.TextField(help_text='Write your article', max_length=2000)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Blogger')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Enter your comments', max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Blogger')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.BlogPost')),
            ],
        ),
    ]
