# Generated by Django 2.0.2 on 2018-02-23 23:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 23, 8, 24, 692563, tzinfo=utc), verbose_name='date posted'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 23, 8, 24, 693142, tzinfo=utc), verbose_name='time posted'),
        ),
    ]
