# Generated by Django 2.0.2 on 2018-02-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20180223_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['-first_name']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-post_time']},
        ),
    ]
